# Generated by Django 3.2.7 on 2022-12-22 21:53

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name="Location's country")),
                ('city', models.CharField(max_length=255, verbose_name="Location's city")),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('house_number', models.PositiveSmallIntegerField(verbose_name='House number')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
