# Generated by Django 3.2.7 on 2022-12-22 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name of company')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info about company')),
                ('tagline', models.CharField(blank=True, max_length=255, null=True, verbose_name='Companies tagline')),
                ('logo', models.ImageField(upload_to='', verbose_name='Companies logo')),
                ('foundation_date', models.DateField(blank=True, null=True, verbose_name='Foundation date')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\+375 \\((29|44|33)\\) [0-9]{3}-[0-9]{2}-[0-9]{2}$')], verbose_name='Phone number')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('locations', models.ManyToManyField(blank=True, null=True, to='core1.Location')),
                ('partners', models.ManyToManyField(blank=True, null=True, related_name='_company_company_partners_+', to='company.Company')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
