# Generated by Django 3.2.7 on 2022-12-23 21:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name of company')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info about company')),
                ('tagline', models.CharField(blank=True, max_length=255, null=True, verbose_name='Companies tagline')),
                ('logo', models.ImageField(upload_to='', verbose_name='Companies logo')),
                ('foundation_date', models.DateField(blank=True, null=True, verbose_name='Foundation date')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\+375 \\((29|44|33)\\) [0-9]{3}-[0-9]{2}-[0-9]{2}$')], verbose_name='Phone number')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Employee name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Employee lastname')),
                ('age', models.CharField(max_length=2, verbose_name='Employee age')),
                ('language', models.CharField(blank=True, choices=[('PY', 'Python'), ('JS', 'JavaScript')], max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ('name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name="Location's country")),
                ('city', models.CharField(max_length=255, verbose_name="Location's city")),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('house_number', models.PositiveSmallIntegerField(verbose_name='House number')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ('country', 'city', 'street', 'house_number'),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('country', 'city', 'street', 'house_number'), name='unique_locations'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.skill'),
        ),
        migrations.AddField(
            model_name='company',
            name='locations',
            field=models.ManyToManyField(to='company.Location'),
        ),
        migrations.AddField(
            model_name='company',
            name='partners',
            field=models.ManyToManyField(related_name='_company_company_partners_+', to='company.Company'),
        ),
    ]
