# Generated by Django 3.2.7 on 2022-12-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='companies',
            field=models.ManyToManyField(related_name='employee', related_query_name='employee', through='company.JobTitle', to='company.Company'),
        ),
    ]
