# Generated by Django 3.2.7 on 2022-12-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('code', models.CharField(blank=True, max_length=2, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='language',
        ),
    ]
