# Generated by Django 3.2.7 on 2022-12-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20221225_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(blank=True, choices=[('PY', 'Python'), ('JS', 'JavaScript')], max_length=20),
        ),
    ]
