# Generated by Django 3.2.7 on 2022-12-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_language_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
