# Generated by Django 3.2.7 on 2022-12-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_employee_languages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'ordering': ('company', 'employee', 'job_title'), 'verbose_name': 'JobTitle', 'verbose_name_plural': 'JobTitles'},
        ),
        migrations.AddConstraint(
            model_name='jobtitle',
            constraint=models.UniqueConstraint(fields=('company_id', 'employee_id'), name='unique_job_title'),
        ),
    ]
