# Generated by Django 3.2.7 on 2023-01-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='job_title',
            field=models.CharField(choices=[('DEVELOPER', 'Developer'), ('TESTER', 'Tester'), ('SALES', 'Sales'), ('PR', 'Project manager'), ('HR', 'HR')], max_length=255, verbose_name='Job title'),
        ),
    ]
