# Generated by Django 3.2.7 on 2023-01-09 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_jobtitle_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.employee', verbose_name='Employee'),
        ),
    ]
