# Generated by Django 3.2.7 on 2022-12-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_jobtitle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
