# Generated by Django 3.2.7 on 2022-12-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_language_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobtitle',
            name='unique_job_title',
        ),
        migrations.AddConstraint(
            model_name='jobtitle',
            constraint=models.UniqueConstraint(fields=('company', 'employee_'), name='unique_job_title'),
        ),
    ]
